CREATE DATABASE crud_adm;

\c crud_adm;

CREATE TABLE IF NOT EXISTS users (
"id" SERIAL PRIMARY KEY,
"name" VARCHAR(20) NOT NULL,
"email" VARCHAR(100) UNIQUE NOT NULL,
"password" VARCHAR(120) NOT NULL,
"admin" BOOLEAN NOT NULL DEFAULT FALSE,
"active" BOOLEAN NOT NULL DEFAULT TRUE
);

\dt;